--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/PushkarOP/CustomCraft
build-by-default: true
branches:
- master
projects:
  CustomCraft:
    path: ""
    libs:
      - src: muqsit/InvMenu/InvMenu
        branch: master
        version: ^4.1.1
...
