name: CustomCraft
authors: [TeamBixby, alvin0319]
main: TeamBixby\CustomCraft\CustomCraft
version: 1.0.0
api: 3.0.0

softdepend:
  - CustomItemLoader # Prevent 'Unmapped ID:metadata combination' error

permissions:
  customcraft.command:
    default: op